stages:
  
  prepare_glyphs:
    cmd: python src/data/prepare_glyphs.py data/raw/glyphs/ data/interim/glyphs/
    deps:
      - data/raw/glyphs/
    outs:
      - data/interim/glyphs/

  prepare_mnist:
    cmd: python src/data/prepare_mnist.py data/raw 50 data/interim/digits.csv data/interim/digits/
    deps:
      - data/raw/MNIST/raw/
    outs:
      - data/interim/digits.csv
      - data/interim/digits/
  
  merge_pictures:
    cmd: python src/data/merge_pictures.py data/interim/glyphs/ data/interim/digits/
    deps:
      - data/interim/glyphs/
      - data/interim/digits/
    outs:
      - data/processed/glyphs/

  clean_data:
    cmd: python src/data/clean_data.py data/raw/glyphs.csv data/interim/data_cleaned.csv
    deps:
      - data/raw/glyphs.csv
    outs:
      - data/interim/data_cleaned.csv

  make_dataset:
    cmd: python -m src.data.make_dataset data/interim/data_cleaned.csv data/interim/digits.csv data/processed/final.csv
    deps:
      - data/interim/data_cleaned.csv
      - data/interim/digits.csv
    outs:
      - data/processed/final.csv

  train_test_split:
    cmd: python src/data/split_train_test.py data/processed/final.csv
    deps:
      - data/processed/final.csv
    outs:
      - data/processed/train_data.csv
      - data/processed/test_data.csv

  train_and_evaluate:
    cmd: python -m src.models.train_and_eval data/processed/train_data.csv data/processed/test_data.csv models/mnist_model.pt models/best_params.json models/test_run.pt reports/figures/
    deps:
      - data/processed/train_data.csv
      - data/processed/test_data.csv
      - models/mnist_model.pt
      - models/best_params.json
    outs:
      - models/test_run.pt
